program Teste_Classes;

uses
  FastMM4,
  Vcl.Forms,
  uTeste in 'uTeste.pas' {Form1},
  FinanceiroPedidoDao in '..\Dao\FinanceiroPedidoDao.pas',
  FinanceiroPedidoModel in '..\Model\FinanceiroPedidoModel.pas',
  Terasoft.Types in '..\Types\Terasoft.Types.pas',
  Interfaces.Conexao in '..\Interfaces\Interfaces.Conexao.pas',
  Terasoft.Utils in '..\Libs\Terasoft.Utils.pas',
  Terasoft.ConstrutorDao in '..\Libs\Terasoft.ConstrutorDao.pas',
  Terasoft.FuncoesTexto in '..\Libs\Terasoft.FuncoesTexto.pas',
  Conexao in 'Conexao.pas',
  WebPedidoModel in '..\Model\WebPedidoModel.pas',
  WebPedidoDao in '..\Dao\WebPedidoDao.pas',
  FuncionarioModel in '..\Model\FuncionarioModel.pas',
  PedidoItensModel in '..\Model\PedidoItensModel.pas',
  PedidoVendaModel in '..\Model\PedidoVendaModel.pas',
  WebPedidoItensModel in '..\Model\WebPedidoItensModel.pas',
  FornecedorDao in '..\Dao\FornecedorDao.pas',
  FuncionarioDao in '..\Dao\FuncionarioDao.pas',
  PedidoItensDao in '..\Dao\PedidoItensDao.pas',
  CalcularImpostosModel in '..\Model\CalcularImpostosModel.pas',
  MovimentoModel in '..\Model\MovimentoModel.pas',
  ProdutosModel in '..\Model\ProdutosModel.pas',
  UsuarioModel in '..\Model\UsuarioModel.pas',
  CalcularImpostosDao in '..\Dao\CalcularImpostosDao.pas',
  MovimentoDao in '..\Dao\MovimentoDao.pas',
  PedidoVendaDao in '..\Dao\PedidoVendaDao.pas',
  CFOPModel in '..\Model\CFOPModel.pas',
  ContasReceberItensModel in '..\Model\ContasReceberItensModel.pas',
  EmpresaModel in '..\Model\EmpresaModel.pas',
  NFItensModel in '..\Model\NFItensModel.pas',
  NFModel in '..\Model\NFModel.pas',
  PortadorModel in '..\Model\PortadorModel.pas',
  ContasReceberItensDao in '..\Dao\ContasReceberItensDao.pas',
  LojasModel in '..\Model\LojasModel.pas',
  LojasDao in '..\Dao\LojasDao.pas',
  AdmCartaoModel in '..\Model\AdmCartaoModel.pas',
  RecebimentoCartaoModel in '..\Model\RecebimentoCartaoModel.pas',
  VendedorModel in '..\Model\VendedorModel.pas',
  VendaCartaoModel in '..\Model\VendaCartaoModel.pas',
  VendaCartaoDao in '..\Dao\VendaCartaoDao.pas',
  AdmCartaoDao in '..\Dao\AdmCartaoDao.pas',
  ContasReceberModel in '..\Model\ContasReceberModel.pas',
  TEFModel in '..\Model\TEFModel.pas',
  ContasReceberDao in '..\Dao\ContasReceberDao.pas',
  TEFDao in '..\Dao\TEFDao.pas',
  CaixaModel in '..\Model\CaixaModel.pas',
  ContaCorrenteModel in '..\Model\ContaCorrenteModel.pas',
  CreditoClienteModel in '..\Model\CreditoClienteModel.pas',
  CreditoClienteUsoModel in '..\Model\CreditoClienteUsoModel.pas',
  CaixaDao in '..\Dao\CaixaDao.pas',
  RecebimentoCartaoDao in '..\Dao\RecebimentoCartaoDao.pas',
  PortadorDao in '..\Dao\PortadorDao.pas',
  ContaCorrenteDao in '..\Dao\ContaCorrenteDao.pas',
  CreditoClienteDao in '..\Dao\CreditoClienteDao.pas',
  CreditoClienteUsoDao in '..\Dao\CreditoClienteUsoDao.pas',
  NFDao in '..\Dao\NFDao.pas',
  NFItensDao in '..\Dao\NFItensDao.pas',
  ProdutosDao in '..\Dao\ProdutosDao.pas',
  CFOPDao in '..\Dao\CFOPDao.pas',
  EmpresaDao in '..\Dao\EmpresaDao.pas',
  UsuarioDao in '..\Dao\UsuarioDao.pas',
  WebPedidoItensDao in '..\Dao\WebPedidoItensDao.pas',
  VendedorDao in '..\Dao\VendedorDao.pas',
  Controllers.Conexao in 'Controllers.Conexao.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TForm1, Form1);
  Application.Run;
end.
