program Teste_Classes;

uses
  FastMM4,
  Vcl.Forms,
  uTeste in 'uTeste.pas' {Form1},
  FinanceiroPedidoDao in '..\Dao\FinanceiroPedidoDao.pas',
  FinanceiroPedidoModel in '..\Model\FinanceiroPedidoModel.pas',
  Terasoft.Types in '..\Types\Terasoft.Types.pas',
  Interfaces.Conexao in '..\Interfaces\Interfaces.Conexao.pas',
  Terasoft.Utils in '..\Libs\Terasoft.Utils.pas',
  Terasoft.ConstrutorDao in '..\Libs\Terasoft.ConstrutorDao.pas',
  Conexao in 'Conexao.pas',
  WebPedidoModel in '..\Model\WebPedidoModel.pas',
  WebPedidoDao in '..\Dao\WebPedidoDao.pas',
  FuncionarioModel in '..\Model\FuncionarioModel.pas',
  PedidoItensModel in '..\Model\PedidoItensModel.pas',
  PedidoVendaModel in '..\Model\PedidoVendaModel.pas',
  WebPedidoItensModel in '..\Model\WebPedidoItensModel.pas',
  FornecedorDao in '..\Dao\FornecedorDao.pas',
  FuncionarioDao in '..\Dao\FuncionarioDao.pas',
  PedidoItensDao in '..\Dao\PedidoItensDao.pas',
  CalcularImpostosModel in '..\Model\CalcularImpostosModel.pas',
  MovimentoModel in '..\Model\MovimentoModel.pas',
  ProdutosModel in '..\Model\ProdutosModel.pas',
  UsuarioModel in '..\Model\UsuarioModel.pas',
  CalcularImpostosDao in '..\Dao\CalcularImpostosDao.pas',
  MovimentoDao in '..\Dao\MovimentoDao.pas',
  PedidoVendaDao in '..\Dao\PedidoVendaDao.pas',
  CFOPModel in '..\Model\CFOPModel.pas',
  ContasReceberItensModel in '..\Model\ContasReceberItensModel.pas',
  EmpresaModel in '..\Model\EmpresaModel.pas',
  NFItensModel in '..\Model\NFItensModel.pas',
  NFModel in '..\Model\NFModel.pas',
  PortadorModel in '..\Model\PortadorModel.pas',
  ContasReceberItensDao in '..\Dao\ContasReceberItensDao.pas',
  LojasModel in '..\Model\LojasModel.pas',
  LojasDao in '..\Dao\LojasDao.pas',
  AdmCartaoModel in '..\Model\AdmCartaoModel.pas',
  RecebimentoCartaoModel in '..\Model\RecebimentoCartaoModel.pas',
  VendedorModel in '..\Model\VendedorModel.pas',
  VendaCartaoModel in '..\Model\VendaCartaoModel.pas',
  VendaCartaoDao in '..\Dao\VendaCartaoDao.pas',
  AdmCartaoDao in '..\Dao\AdmCartaoDao.pas',
  ContasReceberModel in '..\Model\ContasReceberModel.pas',
  TEFModel in '..\Model\TEFModel.pas',
  ContasReceberDao in '..\Dao\ContasReceberDao.pas',
  TEFDao in '..\Dao\TEFDao.pas',
  CaixaModel in '..\Model\CaixaModel.pas',
  ContaCorrenteModel in '..\Model\ContaCorrenteModel.pas',
  CreditoClienteModel in '..\Model\CreditoClienteModel.pas',
  CreditoClienteUsoModel in '..\Model\CreditoClienteUsoModel.pas',
  CaixaDao in '..\Dao\CaixaDao.pas',
  RecebimentoCartaoDao in '..\Dao\RecebimentoCartaoDao.pas',
  PortadorDao in '..\Dao\PortadorDao.pas',
  ContaCorrenteDao in '..\Dao\ContaCorrenteDao.pas',
  CreditoClienteDao in '..\Dao\CreditoClienteDao.pas',
  CreditoClienteUsoDao in '..\Dao\CreditoClienteUsoDao.pas',
  NFDao in '..\Dao\NFDao.pas',
  NFItensDao in '..\Dao\NFItensDao.pas',
  ProdutosDao in '..\Dao\ProdutosDao.pas',
  CFOPDao in '..\Dao\CFOPDao.pas',
  EmpresaDao in '..\Dao\EmpresaDao.pas',
  UsuarioDao in '..\Dao\UsuarioDao.pas',
  WebPedidoItensDao in '..\Dao\WebPedidoItensDao.pas',
  VendedorDao in '..\Dao\VendedorDao.pas',
  Controllers.Conexao in 'Controllers.Conexao.pas',
  ClienteModel in '..\Model\ClienteModel.pas',
  PrecoClienteModel in '..\Model\PrecoClienteModel.pas',
  PrecoUFModel in '..\Model\PrecoUFModel.pas',
  PrecoVendaModel in '..\Model\PrecoVendaModel.pas',
  PrecoVendaProdutoModel in '..\Model\PrecoVendaProdutoModel.pas',
  PromocaoItensModel in '..\Model\PromocaoItensModel.pas',
  ClienteDao in '..\Dao\ClienteDao.pas',
  PrecoUFDao in '..\Dao\PrecoUFDao.pas',
  PromocaoItensDao in '..\Dao\PromocaoItensDao.pas',
  PrecoVendaDao in '..\Dao\PrecoVendaDao.pas',
  PrecoVendaProdutoDao in '..\Dao\PrecoVendaProdutoDao.pas',
  PrecoClienteDao in '..\Dao\PrecoClienteDao.pas',
  TabelaJurosModel in '..\Model\TabelaJurosModel.pas',
  TabelaJurosDao in '..\Dao\TabelaJurosDao.pas',
  SaldoModel in '..\Model\SaldoModel.pas',
  SaldoDao in '..\Dao\SaldoDao.pas',
  Terasoft.FuncoesTexto in '..\Libs\Terasoft.FuncoesTexto.pas',
  GeneratorNewDao in '..\Dao\GeneratorNewDao.pas',
  EntradaItensDao in '..\Dao\EntradaItensDao.pas',
  EntradaModel in '..\Model\EntradaModel.pas',
  EntradaDao in '..\Dao\EntradaDao.pas',
  EntradaItensModel in '..\Model\EntradaItensModel.pas',
  ContasPagarDao in '..\Dao\ContasPagarDao.pas',
  ContasPagarModel in '..\Model\ContasPagarModel.pas',
  ContasPagarItensModel in '..\Model\ContasPagarItensModel.pas',
  ContasPagarItensDao in '..\Dao\ContasPagarItensDao.pas',
  ReservaDao in '..\Dao\ReservaDao.pas',
  ReservaModel in '..\Model\ReservaModel.pas',
  AnexoModel in '..\Model\AnexoModel.pas',
  AnexoDao in '..\Dao\AnexoDao.pas',
  DocumentoDao in '..\Dao\DocumentoDao.pas',
  DocumentoModel in '..\Model\DocumentoModel.pas',
  FluxoCaixaDao in '..\Dao\FluxoCaixaDao.pas',
  FluxoCaixaModel in '..\Model\FluxoCaixaModel.pas',
  FornecedorModel in '..\Model\FornecedorModel.pas',
  BancoModel in '..\Model\BancoModel.pas',
  BancoDao in '..\Dao\BancoDao.pas',
  OSModel in '..\Model\OSModel.pas',
  OSDao in '..\Dao\OSDao.pas',
  SimuladorPrecoModel in '..\Model\SimuladorPrecoModel.pas',
  GrupoModel in '..\Model\GrupoModel.pas',
  GrupoDao in '..\Dao\GrupoDao.pas',
  SubGrupoModel in '..\Model\SubGrupoModel.pas',
  SubGrupoDao in '..\Dao\SubGrupoDao.pas',
  MarcaDao in '..\Dao\MarcaDao.pas',
  MarcaModel in '..\Model\MarcaModel.pas',
  MedidaDao in '..\Dao\MedidaDao.pas',
  MedidaModel in '..\Model\MedidaModel.pas',
  GrupoComissaoModel in '..\Model\GrupoComissaoModel.pas',
  GrupoComissaoDao in '..\Dao\GrupoComissaoDao.pas',
  ProdutoTipoModel in '..\Model\ProdutoTipoModel.pas',
  ProdutoTipoDao in '..\Dao\ProdutoTipoDao.pas',
  LocalizacaoEstoqueDao in '..\Dao\LocalizacaoEstoqueDao.pas',
  LocalizacaoEstoqueModel in '..\Model\LocalizacaoEstoqueModel.pas',
  PedidoCompraModel in '..\Model\PedidoCompraModel.pas',
  PedidoCompraDao in '..\Dao\PedidoCompraDao.pas',
  PedidoCompraItensDao in '..\Dao\PedidoCompraItensDao.pas',
  PedidoCompraItensModel in '..\Model\PedidoCompraItensModel.pas',
  ClientesContatoModel in '..\Model\ClientesContatoModel.pas',
  ClientesContatoDao in '..\Dao\ClientesContatoDao.pas',
  Terasoft.Configuracoes in '..\Libs\Terasoft.Configuracoes.pas',
  DescontoDao in '..\Dao\DescontoDao.pas',
  DescontoModel in '..\Model\DescontoModel.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TForm1, Form1);
  Application.Run;
end.
