unit Terasoft.Framework.Credipar.Analisador.iface.Conts;

interface

  const
    FINANCEIRA_CREDIPAR_NOME             = 'CREDIPAR';
    CONTROLEALTERACOES_CREDIPAR_PROPOSTA = 'PROPOSTA';
    CONTROLEALTERACOES_CREDIPAR_CONTRATO = 'CONTRATO';
    CONTROLEALTERACOES_CREDIPAR_RESULTADOMENSAGEM = 'PROPOSTA.MSG';
    CONTROLEALTERACOES_CREDIPAR_RESULTADOPROCESSAMENTO = 'PROPOSTA.PROC';

    RETORNO_CREDIPAR_LOJA           = 'Credipar.loja';
    RETORNO_CREDIPAR_MENSAGEM       = 'Credipar.mensagem';
    RETORNO_CREDIPAR_CONTRATO       = 'Credipar.contrato';
    RETORNO_CREDIPAR_PROCESSAMENTO  = 'Credipar.processamento';
    RETORNO_CREDIPAR_PREVISAOPGTO   = 'PREVISAOPGTO';
    RETORNO_CREDIPAR_PROPOSTA       = 'Credipar.proposta';
    RETORNO_CREDIPAR_BOLETO         = 'Credipar.boleto';
    RETORNO_CREDIPAR_ERRO           = 'Credipar.erro';

    RETORNO_CREDIPAR_DADOSCLIENTE   = 'Cliente.dados';
    RETORNO_CREDIPAR_DADOSPROPOSTA  = 'Proposta.dados';

    RETORNO_CREDIPAR_RESULTADO      = 'Proposta.resultado';
    RETORNO_CREDIPAR_CONCILIACAO    = 'Proposta.conciliacao';
    RETORNO_CREDIPAR_SIMULACAO      = 'Proposta.simulacao';

    CREDIPAR_TIPODOC_CCB            = 'ADI';
    CREDIPAR_TIPODOC_INFPESSOAL     = 'IP';
    CREDIPAR_TIPODOC_COMPRESIDENCIA = 'CRES';
    CREDIPAR_TIPODOC_COMPRENDA      = 'CREN';
    CREDIPAR_TIPODOC_EXPCREDITO     = 'EXP';
    CREDIPAR_TIPODOC_CARTABACEN     = 'BACEN';
    CREDIPAR_TIPODOC_CONSREGIONAL   = 'CONS';
    CREDIPAR_TIPODOC_CONTRATOSOCIAL = 'SOCIAL';
    CREDIPAR_TIPODOC_SEGURO         = 'SEGURO';
    CREDIPAR_TIPODOC_IR             = 'IR';
    CREDIPAR_TIPODOC_OUTROS         = 'OUT';


    CREDIPAR_LIMITE_ARQUIVO = (2 * 1024 * 1024 );

    FINANCEIRA_STATUS_DESCONHECIDO       = '';
    FINANCEIRA_STATUS_MARCADO_PARA_ENVIO = 'A';
    FINANCEIRA_STATUS_ENVIADO            = 'E';
    FINANCEIRA_STATUS_CANCELADO          = 'C';
    FINANCEIRA_STATUS_ERRO               = 'D';
    FINANCEIRA_STATUS_APROVADO           = 'L';
    FINANCEIRA_STATUS_FINALIZADO         = 'Z';

    CONTROLE_FINANCEIRA_STATUS           = 'Status';


    CREDIPAR_ANEXO_ANALISE       = 'DOC_ANALISE_CREDIPAR';
    CREDIPAR_ANEXO_PROCESSAMENTO = 'DOC_PROC_CREDIPAR';


implementation

end.
