unit Terasoft.Framework.Financeira.Analisador.iface.Consts;

interface

  const
    FINANCEIRA_CREDIPAR_NOME             = 'CREDIPAR';
    FINANCEIRA_TOPONE_NOME               = 'TOPONE';

    CONTROLEALTERACOES_FINANCEIRA_PROPOSTA = 'PROPOSTA';
    CONTROLEALTERACOES_FINANCEIRA_CONTRATO = 'CONTRATO';
    CONTROLEALTERACOES_FINANCEIRA_RESULTADOMENSAGEM = 'PROPOSTA.MSG';
    CONTROLEALTERACOES_FINANCEIRA_RESULTADOPROCESSAMENTO = 'PROPOSTA.PROC';

    CONTROLEALTERACOES_FINANCEIRA_INDICE = 'PROPOSTA.INDICE';
    CONTROLEALTERACOES_FINANCEIRA_VALOR  = 'PROPOSTA.VALOR';

    RETORNO_CREDIPAR_LOJA           = 'Credipar.loja';
    RETORNO_CREDIPAR_MENSAGEM       = 'Credipar.mensagem';
    RETORNO_CREDIPAR_CONTRATO       = 'Credipar.contrato';
    RETORNO_CREDIPAR_PROCESSAMENTO  = 'Credipar.processamento';
    RETORNO_CREDIPAR_PREVISAOPGTO   = 'PREVISAOPGTO';
    RETORNO_CREDIPAR_PROPOSTA       = 'Credipar.proposta';
    RETORNO_FINANCEIRA_BOLETO       = 'Fianceira.boleto';

    RETORNO_FINANCEIRA_ERRO           = 'Financeira.erro';

    RETORNO_CREDIPAR_DADOSCLIENTE   = 'Cliente.dados';
    RETORNO_CREDIPAR_DADOSPROPOSTA  = 'Proposta.dados';

    RETORNO_FINANCEIRA_RESULTADO    = 'Proposta.resultado';

    RETORNO_CREDIPAR_CONCILIACAO    = 'Proposta.conciliacao';
    RETORNO_CREDIPAR_SIMULACAO      = 'Proposta.simulacao';

    TOPONE_TIPODOC_RG             = 'RG';
    TOPONE_TIPODOC_CPF            = 'CPF';
    TOPONE_TIPODOC_CNH            = 'CNH';
    TOPONE_TIPODOC_COMPRES        = 'RES';
    TOPONE_TIPODOC_CCHQ           = 'CCHQ';
    TOPONE_TIPODOC_CONTRATO       = 'CONT';
    TOPONE_TIPODOC_CHEQUE         = 'CHQ';
    TOPONE_TIPODOC_CCB            = 'CCB';
    TOPONE_TIPODOC_OUTROS         = 'OUTR';

    CREDIPAR_TIPODOC_CCB            = 'ADI';
    CREDIPAR_TIPODOC_COMPRESIDENCIA = 'CRES';
    CREDIPAR_TIPODOC_INFPESSOAL     = 'IP';
    CREDIPAR_TIPODOC_COMPRENDA      = 'CREN';
    CREDIPAR_TIPODOC_EXPCREDITO     = 'EXP';
    CREDIPAR_TIPODOC_CARTABACEN     = 'BACEN';
    CREDIPAR_TIPODOC_CONSREGIONAL   = 'CONS';
    CREDIPAR_TIPODOC_CONTRATOSOCIAL = 'SOCIAL';
    CREDIPAR_TIPODOC_SEGURO         = 'SEGURO';
    CREDIPAR_TIPODOC_IR             = 'IR';
    CREDIPAR_TIPODOC_OUTROS         = 'OUT';

    FINANCEIRA_LIMITE_ARQUIVO = (2 * 1024 * 1024 );

    CREDIPAR_LIMITE_ARQUIVO = FINANCEIRA_LIMITE_ARQUIVO;

    FINANCEIRA_STATUS_DESCONHECIDO       = '';
    FINANCEIRA_STATUS_MARCADO_PARA_ENVIO = 'A';
    FINANCEIRA_STATUS_PRE_ENVIADO        = 'B';
    FINANCEIRA_STATUS_ENVIADO            = 'E';
    FINANCEIRA_STATUS_CANCELADO          = 'C';
    FINANCEIRA_STATUS_NEGADA             = 'N';
    FINANCEIRA_STATUS_ERRO               = 'D';
    FINANCEIRA_STATUS_PENDENTE           = 'P';
    FINANCEIRA_STATUS_APROVADO           = 'L';
    FINANCEIRA_STATUS_FINALIZADO         = 'Z';

    CONTROLE_FINANCEIRA_STATUS           = 'Status';


    FINANCEIRA_ANEXO_ANALISE       = 'DOC_ANALISE_';
    FINANCEIRA_ANEXO_PROCESSAMENTO = 'DOC_PROC_';




implementation

end.
