
{$i definicoes.inc}

unit Terasoft.Framework.EventosUso.consts;

interface

  const
    TAMANHOENTROPIA_BITS    = 280;
    TAMANHOENTROPIA_BYTES   = (TAMANHOENTROPIA_BITS div 8); //35
    TAMANHOENTROPIA_BASE32  = (TAMANHOENTROPIA_BITS div 5); //56


    EVENTOUSO_ACAO_SISTEMA     = 'SISTEMA';
    EVENTOUSO_PROPRIEDADE_CONEXAO  = 'CONEXAO.PROPRIEDADE';

    EVENTOUSO_ACAO_CONEXAO     = 'CONEXAO';
    EVENTOUSO_ACAO_LOGIN       = 'AUTENTICACAO';
    EVENTOUSO_ACAO_LOGOFF      = 'DESCONEXAO';

    EVENTOUSO_ACAO_SAIDAFORCADA= 'SAIDAFORCADA';
    EVENTOUSO_ACAO_USERDEADLOCK= 'USERDEADLOCK';
    EVENTOUSO_ACAO_DEADLOCK    = 'DEADLOCK';
    EVENTOUSO_ACAO_REINICIAR   = 'REINICIAR';
    EVENTOUSO_ACAO_SHOW        = 'SHOW';
    EVENTOUSO_ACAO_RELEASE     = 'RELEASE';

    EVENTOUSO_ERRO_LOGIN       = 'FALHAAUTENTICACAO';

    EVENTOUSO_ERRO_EMPRESABLOQ = 'EMPRESABLOQUEADA';

    EVENTOUSO_ERRO_EXCEPTION   = 'EXCEPTION';

implementation

end.

