
{$i definicoes.inc}

unit Terasoft.Framework.EstatisticaUso.consts;

interface

  const
    TAMANHOENTROPIA_BITS    = 280;
    TAMANHOENTROPIA_BYTES   = (TAMANHOENTROPIA_BITS div 8); //35
    TAMANHOENTROPIA_BASE32  = (TAMANHOENTROPIA_BITS div 5); //56


    ESTATISTICAUSO_ACAO_CONEXAO     = 'CONEXAO';
    ESTATISTICAUSO_ACAO_LOGIN       = 'AUTENTICACAO';
    ESTATISTICAUSO_ACAO_LOGOFF      = 'DESCONEXAO';

    ESTATISTICAUSO_ERRO_LOGIN       = 'FALHAAUTENTICACAO';

    ESTATISTICAUSO_ERRO_EMPRESABLOQ = 'EMPRESABLOQUEADA';

implementation

end.

